# Generated by Django 3.2 on 2022-03-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_has_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='units_sold',
            field=models.IntegerField(default=0),
        ),
    ]
