# Generated by Django 3.2 on 2022-03-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_units_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='units_sold',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
    ]
