# Generated by Django 3.2 on 2022-03-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_units_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='units_sold',
        ),
        migrations.AddField(
            model_name='product',
            name='unit_sold',
            field=models.IntegerField(default=0),
        ),
    ]
