# Generated by Django 3.2 on 2022-03-30 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_rename_unit_sold_product_units_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description_header',
        ),
    ]
